# Generated by Django 5.0.2 on 2024-02-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nofie_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
    ]
