# Generated by Django 5.0.2 on 2024-02-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nofie_app', '0002_remove_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='Computer Science', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(default='Computer Science', max_length=100),
        ),
    ]
